export CUDA_VISIBLE_DEVICES=7

model_name=DLinear

python -u run.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_48_4 \
  --model $model_name \
  --data custom \
  --features MS \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 4 \
  --e_layers 3 \
  --d_layers 3 \
  --factor 3 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 1 \
  --batch_size 32 \
  --d_model 512 \
  --des 'Exp' \
  --target 'tp' \
  --itr 1 \
  --learning_rate 0.001 \
  --loss 'MSE' \
  --train_epochs 20 \
  --patience 20 \
  --inverse \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_48_6 \
  --model $model_name \
  --data custom \
  --features MS \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 6 \
  --e_layers 3 \
  --d_layers 3 \
  --factor 3 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 1 \
  --batch_size 32 \
  --d_model 512 \
  --des 'Exp' \
  --target 'tp' \
  --itr 1 \
  --learning_rate 0.001 \
  --loss 'MSE' \
  --train_epochs 20 \
  --patience 20 \
  --inverse \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_48_8 \
  --model $model_name \
  --data custom \
  --features MS \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 8 \
  --e_layers 3 \
  --d_layers 3 \
  --factor 3 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 1 \
  --batch_size 32 \
  --d_model 512 \
  --des 'Exp' \
  --target 'tp' \
  --itr 1 \
  --learning_rate 0.001 \
  --loss 'MSE' \
  --train_epochs 20 \
  --patience 20 \
  --inverse \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_48_10 \
  --model $model_name \
  --data custom \
  --features MS \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 10 \
  --e_layers 3 \
  --d_layers 3 \
  --factor 3 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 1 \
  --batch_size 32 \
  --d_model 512 \
  --des 'Exp' \
  --target 'tp' \
  --itr 1 \
  --learning_rate 0.001 \
  --loss 'MSE' \
  --train_epochs 20 \
  --patience 20 \
  --inverse \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_48_12 \
  --model $model_name \
  --data custom \
  --features MS \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 12 \
  --e_layers 3 \
  --d_layers 3 \
  --factor 3 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 1 \
  --batch_size 32 \
  --d_model 512 \
  --des 'Exp' \
  --target 'tp' \
  --itr 1 \
  --learning_rate 0.001 \
  --loss 'MSE' \
  --train_epochs 20 \
  --patience 20 \
  --inverse \