export CUDA_VISIBLE_DEVICES=7
model_name=PPDformer
patchH=2
# patchW=2
strideH=1
# strideW=4
seq_len=48

python -u run.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_48_4 \
  --model $model_name \
  --data custom \
  --features MS \
  --seq_len $seq_len \
  --label_len 24 \
  --pred_len 4 \
  --e_layers 2 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 6 \
  --des 'Exp' \
  --target 'tp' \
  --d_model 512 \
  --d_ff 512 \
  --patchH $patchH \
  --top_k 5 \
  --normal 0 \
  --dropout 0.1 \
  --attention 1 \
  --patchW 2\
  --strideH $strideH\
  --strideW 2\
  --itr 1 \
  --train_epochs 20 \
  --patience 20 \
  --inverse \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_48_6 \
  --model $model_name \
  --data custom \
  --features MS \
  --seq_len $seq_len \
  --label_len 24 \
  --pred_len 6 \
  --e_layers 2 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 6 \
  --des 'Exp' \
  --target 'tp' \
  --d_model 512 \
  --d_ff 512 \
  --patchH $patchH \
  --top_k 5 \
  --normal 0 \
  --dropout 0.1 \
  --attention 1 \
  --patchW 2\
  --strideH $strideH\
  --strideW 2\
  --itr 1 \
  --train_epochs 20 \
  --patience 20 \
  --inverse \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_48_8 \
  --model $model_name \
  --data custom \
  --features MS \
  --seq_len $seq_len \
  --label_len 24 \
  --pred_len 8 \
  --e_layers 2 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 6 \
  --des 'Exp' \
  --target 'tp' \
  --d_model 512 \
  --d_ff 512 \
  --patchH $patchH \
  --top_k 5 \
  --normal 0 \
  --dropout 0.1 \
  --attention 1 \
  --patchW 2\
  --strideH $strideH\
  --strideW 2\
  --itr 1 \
  --train_epochs 20 \
  --patience 20 \
  --inverse \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_48_10 \
  --model $model_name \
  --data custom \
  --features MS \
  --seq_len $seq_len \
  --label_len 24 \
  --pred_len 10 \
  --e_layers 2 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 6 \
  --des 'Exp' \
  --target 'tp' \
  --d_model 512 \
  --d_ff 512 \
  --patchH $patchH \
  --top_k 5 \
  --normal 0 \
  --dropout 0.1 \
  --attention 1 \
  --patchW 2\
  --strideH $strideH\
  --strideW 2\
  --itr 1 \
  --train_epochs 20 \
  --patience 20 \
  --inverse \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_48_12 \
  --model $model_name \
  --data custom \
  --features MS \
  --seq_len $seq_len \
  --label_len 24 \
  --pred_len 12 \
  --e_layers 2 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 6 \
  --des 'Exp' \
  --target 'tp' \
  --d_model 512 \
  --d_ff 512 \
  --patchH $patchH \
  --top_k 5 \
  --normal 0 \
  --dropout 0.1 \
  --attention 1 \
  --patchW 2\
  --strideH $strideH\
  --strideW 2\
  --itr 1 \
  --train_epochs 20 \
  --patience 20 \
  --inverse \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_24_6 \
  --model $model_name \
  --data custom \
  --features MS \
  --seq_len 24 \
  --label_len 12 \
  --pred_len 6 \
  --e_layers 2 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 6 \
  --des 'Exp' \
  --target 'tp' \
  --d_model 512 \
  --d_ff 512 \
  --patchH $patchH \
  --top_k 5 \
  --normal 0 \
  --dropout 0.1 \
  --attention 1 \
  --patchW 2\
  --strideH $strideH\
  --strideW 2\
  --itr 1 \
  --train_epochs 20 \
  --patience 20 \
  --inverse \