export CUDA_VISIBLE_DEVICES=2

model_name=Informer_prob

python -u run_probloss.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_24_4_MS \
  --model $model_name \
  --data Zero_y_Dataset_Custom \
  --features MS \
  --seq_len 24 \
  --label_len 12 \
  --pred_len 4 \
  --e_layers 3 \
  --d_layers 3 \
  --factor 5 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 1 \
  --des 'Exp' \
  --target 'tp' \
  --itr 1 \
  --train_epochs 20 \
  --patience 20 \
  --inverse \

  python -u run_probloss.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_24_6_MS \
  --model $model_name \
  --data Zero_y_Dataset_Custom \
  --features MS \
  --seq_len 24 \
  --label_len 12 \
  --pred_len 6 \
  --e_layers 3 \
  --d_layers 3 \
  --factor 5 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 1 \
  --des 'Exp' \
  --target 'tp' \
  --itr 1 \
  --train_epochs 20 \
  --patience 20 \
  --inverse \

  python -u run_probloss.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_24_8_MS \
  --model $model_name \
  --data Zero_y_Dataset_Custom \
  --features MS \
  --seq_len 24 \
  --label_len 12 \
  --pred_len 8 \
  --e_layers 3 \
  --d_layers 3 \
  --factor 5 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 1 \
  --des 'Exp' \
  --target 'tp' \
  --itr 1 \
  --train_epochs 20 \
  --patience 20 \
  --inverse \

  python -u run_probloss.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_24_10_MS \
  --model $model_name \
  --data Zero_y_Dataset_Custom \
  --features MS \
  --seq_len 24 \
  --label_len 12 \
  --pred_len 10 \
  --e_layers 3 \
  --d_layers 3 \
  --factor 5 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 1 \
  --des 'Exp' \
  --target 'tp' \
  --itr 1 \
  --train_epochs 20 \
  --patience 20 \
  --inverse \

  python -u run_probloss.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_24_12_MS \
  --model $model_name \
  --data Zero_y_Dataset_Custom \
  --features MS \
  --seq_len 24 \
  --label_len 12 \
  --pred_len 12 \
  --e_layers 3 \
  --d_layers 3 \
  --factor 5 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 1 \
  --des 'Exp' \
  --target 'tp' \
  --itr 1 \
  --train_epochs 20 \
  --patience 20 \
  --inverse \

  python -u run_probloss.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_48_4_MS \
  --model $model_name \
  --data Zero_y_Dataset_Custom \
  --features MS \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 4 \
  --e_layers 3 \
  --d_layers 3 \
  --factor 5 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 1 \
  --des 'Exp' \
  --target 'tp' \
  --itr 1 \
  --train_epochs 20 \
  --patience 20 \
  --inverse \

  python -u run_probloss.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_48_6_MS \
  --model $model_name \
  --data Zero_y_Dataset_Custom \
  --features MS \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 6 \
  --e_layers 3 \
  --d_layers 3 \
  --factor 5 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 1 \
  --des 'Exp' \
  --target 'tp' \
  --itr 1 \
  --train_epochs 20 \
  --patience 20 \
  --inverse \

  python -u run_probloss.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_48_8_MS \
  --model $model_name \
  --data Zero_y_Dataset_Custom \
  --features MS \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 8 \
  --e_layers 3 \
  --d_layers 3 \
  --factor 5 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 1 \
  --des 'Exp' \
  --target 'tp' \
  --itr 1 \
  --train_epochs 20 \
  --patience 20 \
  --inverse \

  python -u run_probloss.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_48_10_MS \
  --model $model_name \
  --data Zero_y_Dataset_Custom \
  --features MS \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 10 \
  --e_layers 3 \
  --d_layers 3 \
  --factor 5 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 1 \
  --des 'Exp' \
  --target 'tp' \
  --itr 1 \
  --train_epochs 20 \
  --patience 20 \
  --inverse \

  python -u run_probloss.py \
  --task_name long_term_forecast \
  --is_training 0  \
  --root_path ./dataset/Rain/ \
  --data_path JFNG_data_15min.csv \
  --model_id rain_48_12_MS \
  --model $model_name \
  --data Zero_y_Dataset_Custom \
  --features MS \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 12 \
  --e_layers 3 \
  --d_layers 3 \
  --factor 5 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 1 \
  --des 'Exp' \
  --target 'tp' \
  --itr 1 \
  --train_epochs 20 \
  --patience 20 \
  --inverse \